[package]
name = "graphrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
dot-writer = "0.1.3"
itertools = "0.11.0"
thiserror = "1.0.50"
